/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as PolicySlugRouteImport } from './routes/policy.$slug'
import { Route as CollectionCategoryRouteImport } from './routes/collection.$category'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSalesRouteImport } from './routes/admin/sales'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminDiscountsIndexRouteImport } from './routes/admin/discounts/index'
import { Route as AdminBlogsIndexRouteImport } from './routes/admin/blogs/index'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminProductsIdRouteImport } from './routes/admin/products/$id'
import { Route as AdminDiscountsNewRouteImport } from './routes/admin/discounts/new'
import { Route as AdminBlogsNewRouteImport } from './routes/admin/blogs/new'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicySlugRoute = PolicySlugRouteImport.update({
  id: '/policy/$slug',
  path: '/policy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionCategoryRoute = CollectionCategoryRouteImport.update({
  id: '/collection/$category',
  path: '/collection/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminDiscountsIndexRoute = AdminDiscountsIndexRouteImport.update({
  id: '/discounts/',
  path: '/discounts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsIndexRoute = AdminBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsNewRoute = AdminDiscountsNewRouteImport.update({
  id: '/discounts/new',
  path: '/discounts/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsNewRoute = AdminBlogsNewRouteImport.update({
  id: '/blogs/new',
  path: '/blogs/new',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/collection/$category': typeof CollectionCategoryRoute
  '/policy/$slug': typeof PolicySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/discounts/new': typeof AdminDiscountsNewRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/discounts/': typeof AdminDiscountsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/collection/$category': typeof CollectionCategoryRoute
  '/policy/$slug': typeof PolicySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/discounts/new': typeof AdminDiscountsNewRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/blogs': typeof AdminBlogsIndexRoute
  '/admin/discounts': typeof AdminDiscountsIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/sales': typeof AdminSalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/collection/$category': typeof CollectionCategoryRoute
  '/policy/$slug': typeof PolicySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/discounts/new': typeof AdminDiscountsNewRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/discounts/': typeof AdminDiscountsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/shop'
    | '/admin/orders'
    | '/admin/sales'
    | '/admin/settings'
    | '/blog/$slug'
    | '/collection/$category'
    | '/policy/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/blogs/new'
    | '/admin/discounts/new'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/blogs/'
    | '/admin/discounts/'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/shop'
    | '/admin/sales'
    | '/admin/settings'
    | '/blog/$slug'
    | '/collection/$category'
    | '/policy/$slug'
    | '/product/$slug'
    | '/admin'
    | '/blog'
    | '/admin/blogs/new'
    | '/admin/discounts/new'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/blogs'
    | '/admin/discounts'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/shop'
    | '/admin/orders'
    | '/admin/sales'
    | '/admin/settings'
    | '/blog/$slug'
    | '/collection/$category'
    | '/policy/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/blogs/new'
    | '/admin/discounts/new'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/admin/blogs/'
    | '/admin/discounts/'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  ShopRoute: typeof ShopRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CollectionCategoryRoute: typeof CollectionCategoryRoute
  PolicySlugRoute: typeof PolicySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy/$slug': {
      id: '/policy/$slug'
      path: '/policy/$slug'
      fullPath: '/policy/$slug'
      preLoaderRoute: typeof PolicySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$category': {
      id: '/collection/$category'
      path: '/collection/$category'
      fullPath: '/collection/$category'
      preLoaderRoute: typeof CollectionCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/discounts/': {
      id: '/admin/discounts/'
      path: '/discounts'
      fullPath: '/admin/discounts/'
      preLoaderRoute: typeof AdminDiscountsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs/': {
      id: '/admin/blogs/'
      path: '/blogs'
      fullPath: '/admin/blogs/'
      preLoaderRoute: typeof AdminBlogsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/products/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts/new': {
      id: '/admin/discounts/new'
      path: '/discounts/new'
      fullPath: '/admin/discounts/new'
      preLoaderRoute: typeof AdminDiscountsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs/new': {
      id: '/admin/blogs/new'
      path: '/blogs/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AdminBlogsNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminOrdersRouteChildren {
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminSalesRoute: typeof AdminSalesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogsNewRoute: typeof AdminBlogsNewRoute
  AdminDiscountsNewRoute: typeof AdminDiscountsNewRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminBlogsIndexRoute: typeof AdminBlogsIndexRoute
  AdminDiscountsIndexRoute: typeof AdminDiscountsIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminSalesRoute: AdminSalesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogsNewRoute: AdminBlogsNewRoute,
  AdminDiscountsNewRoute: AdminDiscountsNewRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminBlogsIndexRoute: AdminBlogsIndexRoute,
  AdminDiscountsIndexRoute: AdminDiscountsIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  ShopRoute: ShopRoute,
  BlogSlugRoute: BlogSlugRoute,
  CollectionCategoryRoute: CollectionCategoryRoute,
  PolicySlugRoute: PolicySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
